[package]
name = "huddle-core"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.56", features = [
    "mdns", "identify", "ping", "request-response",
    "tcp", "noise", "yamux", "tokio", "ed25519", "macros", "gossipsub",
] }
vodozemac = "0.10"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rusqlite = { version = "0.39", features = ["bundled"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = "0.1"
sha2 = "0.11"
hex = "0.4"
dirs = "6"
rand = "0.8"
futures = "0.3"
async-trait = "0.1"
argon2 = "0.5"
chacha20poly1305 = "0.10"
base64 = "0.22"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
